/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lvq_backpro;

/**
 *
 * @author ACER
 */
public class FrameDepan extends javax.swing.JFrame {

    /**
     * Creates new form FrameUtama
     */
    public FrameDepan() {
        initComponents();
        s = null;
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scanData = new javax.swing.JButton();
        lvq = new javax.swing.JButton();
        backpro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Utama");

        scanData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        scanData.setText("Scan Data");
        scanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scanDataActionPerformed(evt);
            }
        });

        lvq.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lvq.setText("LVQ");
        lvq.setMaximumSize(new java.awt.Dimension(113, 23));
        lvq.setMinimumSize(new java.awt.Dimension(113, 23));
        lvq.setPreferredSize(new java.awt.Dimension(113, 23));
        lvq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvqActionPerformed(evt);
            }
        });

        backpro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backpro.setText("Backpropagation");
        backpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backproActionPerformed(evt);
            }
        });

        jLabel1.setText("MSAF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(scanData, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backpro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scanData, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lvq, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backpro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void scanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scanDataActionPerformed
        // TODO add your handling code here:
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                FrameData fD = new FrameData();
//                fD.setVisible(true);
//
//                System.out.println("ScanData");
//                System.out.println(s);
//            }
//        });
        FrameData fD = new FrameData();
        fD.setVisible(true);
        fD.frDepan = this;
        System.out.println("ScanData");
        System.out.println(s);

    }//GEN-LAST:event_scanDataActionPerformed

    private void backproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backproActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameBackpro().setVisible(true);

            }
        });
    }//GEN-LAST:event_backproActionPerformed

    private void lvqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvqActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameLvq().setVisible(true);
            }
        });
    }//GEN-LAST:event_lvqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDepan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDepan().setVisible(true);
            }
        });
    }

    //Variables
    public static DataManagement data = new DataManagement();
    public static String s;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lvq;
    private javax.swing.JButton scanData;
    // End of variables declaration//GEN-END:variables
}
