/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lvq_backpro;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import jxl.Sheet;
import jxl.Workbook;
import sun.swing.BakedArrayList;

/**
 *
 * @author ACER
 */
public class FrameBackproUji extends javax.swing.JFrame {

    /**
     * Creates new form FrameLvqUji
     */
    public FrameBackproUji() {
        initComponents();
        fileChooser.setFileFilter(new FileNameExtensionFilter("MS Excel Documents(*.xls, *.xlsx)", "xls", "xlsx"));
        ImageIcon icon = new ImageIcon(getClass().getResource("/lvq_backpro/neural.png"));
        setIconImage(icon.getImage());
        lihatGrafikButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pilihDataButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataUjiTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        testButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasilTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        errorTextField = new javax.swing.JTextField();
        akurasiTextField = new javax.swing.JTextField();
        lihatGrafikButton = new javax.swing.JButton();

        fileChooser.setCurrentDirectory(new java.io.File("C:\\Users\\ACER\\Documents\\NetBeansProjects\\LVQ_Backpro"));
        fileChooser.setDialogTitle("Pilih Data Uji");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backpropagation Pengujian");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pengujian Backpropagation");

        pilihDataButton.setText("Pilih Data Uji");
        pilihDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihDataButtonActionPerformed(evt);
            }
        });

        dataUjiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataUjiTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Data Uji");

        testButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        testButton.setForeground(new java.awt.Color(51, 204, 0));
        testButton.setText("Uji");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        hasilTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(hasilTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Error");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Akurasi");

        errorTextField.setEditable(false);
        errorTextField.setBackground(new java.awt.Color(255, 255, 255));
        errorTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        akurasiTextField.setEditable(false);
        akurasiTextField.setBackground(new java.awt.Color(255, 255, 255));
        akurasiTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        akurasiTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akurasiTextFieldActionPerformed(evt);
            }
        });

        lihatGrafikButton.setText("Lihat Grafik");
        lihatGrafikButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatGrafikButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pilihDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator2)
                    .addComponent(testButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(errorTextField)
                                            .addComponent(akurasiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lihatGrafikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pilihDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(errorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(akurasiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lihatGrafikButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void akurasiTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akurasiTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akurasiTextFieldActionPerformed

    private void pilihDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihDataButtonActionPerformed
        // TODO add your handling code here:
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            excelFile = fileChooser.getSelectedFile();
            try {
                // Tampikan data
                muatData(excelFile);

                dataUji = new DataManagement();
                dataUji.setInputFile(excelFile.toString());
                dataUji.read2();
                dataUji.normalisasi();
            } catch (Exception ex) {
                System.out.println("Terdapat masalah dalam akses file " + excelFile.getAbsolutePath());
            }
        } else {
            System.out.println("Akses file dibatalkan");
        }
    }//GEN-LAST:event_pilihDataButtonActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
        try {
            //testing data
            backpro.test(dataUji);
            TableModel model = new DefaultTableModel(backpro.hasil.length, 3);

            for (int j = 0; j < model.getRowCount(); j++) {
                model.setValueAt(j + 1, j, 0);
                model.setValueAt(backpro.hasil[0][j], j, 1);
                model.setValueAt(backpro.hasil[1][j], j, 2);
                if (backpro.hasil[0][j] != backpro.hasil[1][j]) {
                    model.setValueAt(backpro.hasil[0][j] + "***", j, 1);
                    model.setValueAt(backpro.hasil[1][j] + "***", j, 2);
                }

            }

            hasilTable.setModel(model);
            JTableHeader th = hasilTable.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            TableColumn tc = tcm.getColumn(0);
            tc.setHeaderValue("No");
            tc = tcm.getColumn(1);
            tc.setHeaderValue("Data Aktual");
            tc = tcm.getColumn(2);
            tc.setHeaderValue("Hasil Prediksi");
            th.repaint();
            errorTextField.setText(String.valueOf(backpro.error));
            akurasiTextField.setText(String.valueOf(backpro.akurasi));
            lihatGrafikButton.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(new JFrame(),
                    "Harap di cek lagi .... !",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_testButtonActionPerformed

    private void lihatGrafikButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatGrafikButtonActionPerformed
        // TODO add your handling code here:
        backpro.tampilkanGrafikPengujian();
    }//GEN-LAST:event_lihatGrafikButtonActionPerformed

    private void muatData(File file) {
        File excelFile = file;

        // buat model untuk file excel
        if (excelFile.exists()) {
            try {
                Workbook workbook = Workbook.getWorkbook(excelFile);
                Sheet sheet = workbook.getSheets()[0];

                TableModel model = new DefaultTableModel(sheet.getRows() - 1, sheet.getColumns());
                for (int row = 0; row < model.getRowCount(); row++) {
                    for (int column = 0; column < model.getColumnCount(); column++) {
                        String content = sheet.getCell(column, row + 1).getContents();
                        model.setValueAt(content, row, column);
                    }
                }
                Object[] columnNames = new Object[sheet.getColumns()];
                for (int i = 0; i < sheet.getColumns(); i++) {
                    columnNames[i] = sheet.getCell(i, 0).getContents();
                }

                dataUjiTable.setModel(model);
                JTableHeader th = dataUjiTable.getTableHeader();
                TableColumnModel tcm = th.getColumnModel();
                TableColumn tc;
                for (int i = 0; i < tcm.getColumnCount(); i++) {
                    tc = tcm.getColumn(i);
                    tc.setHeaderValue(columnNames[i]);
                }

                th.repaint();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "File does not exist");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBackproUji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBackproUji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBackproUji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBackproUji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBackproUji().setVisible(true);
            }
        });
    }

    //Variables
    File excelFile = null;
    Backpropagation3 backpro;
    String path;
    DataManagement dataUji;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField akurasiTextField;
    private javax.swing.JTable dataUjiTable;
    private javax.swing.JTextField errorTextField;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTable hasilTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton lihatGrafikButton;
    private javax.swing.JButton pilihDataButton;
    private javax.swing.JButton testButton;
    // End of variables declaration//GEN-END:variables
}
